# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function rescales a vector of numerical values into the unit interval
#' [0,1] using a C++ implementation for efficiency.
#'
#' @name minmax_scaler
#' @param x a numeric vector, preferably of feature values computed by other functions in sawlog
#' @return x a numeric vector, rescaled into the [0,1] unit interval
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- minmax_scaler(x)
#'
minmax_scaler <- function(x) {
    .Call('_sawlog_minmax_scaler', PACKAGE = 'sawlog', x)
}

#' This function rescales a vector of numerical values into z-scores using a C++
#' implementation for efficiency.
#'
#' @name zscore_scaler
#' @param x a numeric vector, preferably of feature values computed by other functions in sawlog
#' @return x a numeric vector, rescaled into z-score range
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- zscore_scaler(x)
#'
zscore_scaler <- function(x) {
    .Call('_sawlog_zscore_scaler', PACKAGE = 'sawlog', x)
}

#' This function rescales a vector of numerical values with a Sigmoidal transformation
#' using a C++ implementation for efficiency.
#'
#' @name sigmoid_scaler
#' @param x a numeric vector, preferably of feature values computed by other functions in sawlog
#' @return x a numeric vector, rescaled into Sigmoidal range
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- sigmoid_scaler(x)
#'
sigmoid_scaler <- function(x) {
    .Call('_sawlog_sigmoid_scaler', PACKAGE = 'sawlog', x)
}

#' This function rescales a vector of numerical values with an outlier-robust
#' Sigmoidal transformation using a C++ implementation for efficiency.
#'
#' @name robustsigmoid_scaler
#' @param x a numeric vector, preferably of feature values computed by other functions in sawlog
#' @return x a numeric vector, rescaled into Sigmoidal range
#' @author Trent Henderson
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- robustsigmoid_scaler(x)
#'
robustsigmoid_scaler <- function(x) {
    .Call('_sawlog_robustsigmoid_scaler', PACKAGE = 'sawlog', x)
}

#' This function rescales a vector of numerical values by subtracting the mean using a C++
#' implementation for efficiency.
#'
#' @name mean_scaler
#' @param x a numeric vector, preferably of feature values computed by other functions in sawlog
#' @return x a numeric vector, rescaled into x-mean range
#' @author Trent Henderson
#' @export
#' @examples
#' x <- 1 + 0.5 * 1:1000 + arima.sim(list(ma = 0.5), n = 1000)
#' outs <- mean_scaler(x)
#'
mean_scaler <- function(x) {
    .Call('_sawlog_mean_scaler', PACKAGE = 'sawlog', x)
}

